spring:
  application:
    name: app
  datasource:
    users:
      jdbc-url: jdbc:postgresql://localhost:5433/shard1_db
      username: postgres_admin
      password: postgres_admin
      driver-class-name: org.postgresql.Driver
    products:
      jdbc-url: jdbc:postgresql://localhost:5434/shard2_db
      username: postgres_admin
      password: postgres_admin
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS