networks:
  postgres:
    driver: bridge

services:
  master:
    image: postgres
    container_name: master
    networks:
      - postgres
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: postgres_admin
      POSTGRES_DB: postgres_db
      PGDATA: /data
    volumes:
      - ./master/pgdata:/data
      - ./master/config:/config
      - ./master/archive:/mnt/server/archive
      - ./master/create-replication-user.sql:/docker-entrypoint-initdb.d/create-replication-user.sql
    ports:
      - "5433:5432"
    command: ["-c", "config_file=/config/postgresql.conf"]

  slave:
    image: postgres
    container_name: slave
    networks:
      - postgres
    environment:
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: postgres_admin
      POSTGRES_DB: postgres_db
      PGDATA: /data
    volumes:
      - ./slave/pgdata:/data
      - ./slave/config:/config
      - ./slave/archive:/mnt/server/archive
      - ./slave/init-replication.sh:/docker-entrypoint-initdb.d/init-replication.sh
    ports:
      - "5434:5432"
    command: ["-c", "config_file=/config/postgresql.conf"]