spring:
  application:
    name: app
  datasource:
    master:
      jdbc-url: jdbc:postgresql://localhost:5433/postgres_db
      username: postgres_admin
      password: postgres_admin
      driver-class-name: org.postgresql.Driver
    slave:
      jdbc-url: jdbc:postgresql://localhost:5434/postgres_db
      username: postgres_admin
      password: postgres_admin
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS